# Remote theme directory
remote_theme: analytics-link/analytics-link.github.io

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme

#-------------------------------
# General Site Settings
title: Andrew Kelly
description: "Greetings, I'm Andrew, a seasoned technical translator with over a decade of expertise in the software industry. Recently accredited as a proficient data analyst, I bring a wealth of experience to the table. My data science portfolio highlights recent projects with significant business impact. Feel free to delve into my GitHub and LinkedIn profiles, or simply download my resume using the links provided below!"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

#-------------------------------
# About Section
subtitle: Data Science <span style="color:#f58506"> Portfolio </span>
location: "Landau (RP), Germany"
resume_url: /docs/resume.docx
avatar_image: /img/AK2.png

#-------------------------------
# Contact links
linkedln: "https://www.linkedin.com/in/andrew-kelly-704505211" # Add your linkedln handle
github: "https://github.com/KellyAndrew"  # Add your github handle

paginate: 6
paginate_path: "/page/:num"

sass:
  sass_dir: _sass
  style: compressed # possible values: nested expanded compact compressed

defaults:
  - scope:
      type: posts
    values:
      layout: post
      read_time: true
      share: false


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

